/**
 * @file debug_uart.c
 * @brief Implementation of the debug UART module.
 *
 * This module implements a simple UART debug interface for sending strings via UART2.
 * It relies on HAL_UART_Transmit to send data. UART2 is assumed to be already configured
 * by CubeMX, and the UART handle "huart2" must be available.
 */

#include "debug_uart.h"
#include "stm32f4xx_hal.h"
#include "main.h"  // Includes declaration for huart2
#include <string.h>

// External declaration of the UART handle (defined in main.c or generated by CubeMX)
extern UART_HandleTypeDef huart2;

void debug_uart_init(void)
{
    // In most cases, initialization for UART2 is handled by CubeMX.
    // This function exists for logical consistency.
}

int debug_uart_print(const char* msg)
{
    if (msg == 0) {
        return -1;
    }

    uint16_t len = (uint16_t)strlen(msg);
    // Transmit the string over UART2 with a timeout of 100 ms.
    if (HAL_UART_Transmit(&huart2, (uint8_t*)msg, len, 100) == HAL_OK)
    {
        return 0;
    }
    return -1;
}
